[package]
name = "crabsweeper"
version = "1.0.0"
edition = "2024"

[dependencies]
minesweeprs = { path = "lib/minesweeprs" } # Local copy of unmaintained crate: https://github.com/cpcloud/minesweep-rs
macroquad = "0.4.14"
unicode-width = "0.2.2"
rand = { version = "0.10.1", default-features = false, features = ["std_rng"] }
rand_pcg = "0.10.2"
deterministic-hash = "1.0.2"
image = "0.24.9"

[features]
default = []
emoji_grid = []
custom_rule_generator = []
